Translate `NoClassDefFoundError` and `ClassNotFoundException` to warn that the plugin may be loaded by a wrong server if the plugin is trying to use a class that doesn't exist in the current Turms server